version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data1

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings  # variables for pytest
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
  nginx:
    restart: always
    build:
      context: ./nginx/Local
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core.settings worker -l info
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
      - redis
      - web


volumes:
  db:
    driver: local