version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data1
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core.settings worker -l info
    volumes:
      - ./app:/app

    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
      - redis
      - web

volumes:
  db:
    driver: local