# Generated by Django 4.2.8 on 2023-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('JR', 'NO OTHERS)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=256, unique=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
