# Generated by Django 5.0 on 2024-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_is_active_alter_phonenumbers_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
