# Generated by Django 5.0 on 2024-02-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_birth_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
