name: Upload to EC2

on:

  workflow_run:
      workflows: [ "CI Pipeline" ]
      types:
        - completed

concurrency:
  group: main
  cancel-in-progress: true


jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy
        run: |
            ls
            cd Sportsy/
            sudo docker-compose up --build
