name: CI Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/aws-secretsmanager-get-secrets@v1
        id: get-aws-secret 
        with:
          secret-ids: my-production-secrets

      - name: Set environment variables using a shell script
        run: |
          cat << EOF > set_env_vars.sh
          $(echo ${{ steps.get-aws-secret.outputs.secretValue }} | jq -r 'to_entries | .[] | "export \(.key)=\(.value)"')
          EOF
          . ./set_env_vars.sh
      - uses: actions/checkout@v3

      - name: Build and run services
        working-directory: .
        run: docker-compose up -d --build

      - name: Run tests
        working-directory: .
        run: docker-compose run --rm web python manage.py test

      - name: Stop services
        run: docker-compose down

