name: CI Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
        DJANGO_PAGINATION_LIMIT: ${{ secrets.DJANGO_PAGINATION_LIMIT }} 
    steps:
      - uses: actions/checkout@v3

      - name: Check secrets
        run: | 
          echo $SECRET_KEY
          echo $DJANGO_DEBUG
      - name: Build and run services
        working-directory: .

        run: docker-compose up -d --build

      - name: Run tests
        working-directory: .

        run: |
          echo $SECRET_KEY
          docker-compose run --rm -e SECRET_KEY=${{ secrets.SECRET_KEY }} web pytest

      - name: Stop services
        run: docker-compose down

