name: CI Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/aws-secretsmanager-get-secrets@v1
        id: get-aws-secret 
        with:
          secret-ids: |
            SECRET_KEY,  secret/key
  
      - name: Set environment variables using a shell script
        run: |
          run: echo "Secret Value: $MY_SECRET_NAME "    
      - uses: actions/checkout@v3

      - name: Build and run services
        working-directory: .
        run: docker-compose up -d --build

      - name: Run tests
        working-directory: .
        run: docker-compose run --rm web python manage.py test

      - name: Stop services
        run: docker-compose down

